[project]
name = "pypowsybl2grid"
version = "0.3.1"
description = "An integration between Grid2op and PyPowSybl"
authors = [
    { name = "Geoffroy Jamgotchian", email = "geoffroy.jamgotchian@rte-france.com" },
    { name = "Benjamin Donnot", email = "benjamin.donnot@rte-france.com" },
]
readme = "README.md"
license = { text = "MPL-2.0" }
requires-python = ">=3.9"
dependencies = [
    "numpy==1.26.4",
    "grid2op>=1.10.5,<=1.12.2",
    "sortedcontainers>=2.4.0",
]
[dependency-groups]
dev = [
    "pytest>=8.3.3",
    "mypy>=1.11.2",
    "ruff>=0.1.0",
    "isort>=5.12.0",
    "prek>=0.3.6",
]

[project.optional-dependencies]
pypowsybl = ["pypowsybl>=1.11.0,<1.15.0"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
