name: PR

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v3

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - run: uv sync --all-extras

      - run: uv run ruff check .
      - run: uv run ruff format --check .

  test:
    runs-on: ubuntu-22.04
    needs: lint
    steps:
      - name: Install Ubuntu packages
        run: |
          sudo apt update
          sudo apt -y install maven

      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v3

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - run: uv sync --all-extras
      - run: uv run pytest
